# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: GitHub Metrics
on:
  # スケジュール実行（6時間ごとに実行）
  schedule: [{cron: "0 */6 * * *"}]
  # 手動でワークフローを実行できるようにする
  workflow_dispatch:
  # (任意) master/mainブランチにプッシュされた時も実行
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHubトークン
          token: ${{ secrets.METRICS_TOKEN }}

          # 表示するプラグインを有効化
          plugin_isocalendar: yes
          plugin_languages: yes

          # isocalendarプラグインのオプション
          plugin_isocalendar_duration: half-year # 表示期間を半年に変更

          # languagesプラグインのオプション（任意でカスタマイズ可能）
          plugin_languages_limit: 8 # 表示する言語数を8に制限
