name: GitHub Metrics
on:
  # 1日ごと
  schedule: [{cron: "0 0 * * *"}]
  # 手動でワークフローを実行できるようにする
  workflow_dispatch:
  # (任意) master/mainブランチにプッシュされた時も実行
  push: {branches: ["master", "main"]}
  
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""

          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
