# Visit https://github.com/lowlighter/metrics/blob/master/action.yml for full reference
name: Metrics - Isometric Commit Calendar
on:
  # スケジュール実行（6時間ごとに実行）
  schedule: [{cron: "0 */6 * * *"}]
  # 手動でワークフローを実行できるようにする
  workflow_dispatch:
  # (任意) master/mainブランチにプッシュされた時も実行
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions: # <-- このブロックを追加します
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # GitHubトークン
          token: ${{ secrets.METRICS_TOKEN }}

          # Isometric Commit Calendarのみを生成する設定
          base: "" 
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year # 1年分を表示する

          # 出力するファイル名
          filename: metrics.plugin.isocalendar.fullyear.svg
